---
name: alpine

on: [push]

jobs:
  compile:

    name: GRASS GIS extension installation check

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v7
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: osgeo/grass-gis:releasebranch_8_3-alpine
          options: -v ${{ github.workspace }}:/src
          run: |
            bash /src/.github/workflows/test_extension_installation.sh

    # the workflow requires permissions that need to be granted by the parent job:
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read
