---
name: alpine

on: [push]

jobs:
  compile:

    name: GRASS GIS extension installation check

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: osgeo/grass-gis:releasebranch_8_3-alpine
          options: -v ${{ github.workspace }}:/src
          run: |
            bash /src/.github/workflows/test_extension_installation.sh
